spring:
  application:
    name: cards
  datasource:
#    url: jdbc:mysql://localhost:3308/cardsdb
#    username: root
#    password: root
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8071/
  sql:
    init:
      mode: always
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
server:
  port: 9000
  forward-headers-strategy: framework
management:
  endpoints:
    web:
      exposure:
        include: "*"
  shutdown:
    access: unrestricted
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
#build:
#  version: "1.0-dev"
#cards:
#  message: "Welcome to SomeBank's related local API"
#  contactDetails:
#    name: John Doe - Developer
#    email: JohnDoe@example.com
#  onCallSupport:
#    - (555)555-1234
#    - (555)523-4321
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "cards"
    description: "SomeBank microservice responsible for cards"
    version: "1.0.0"
logging:
  level:
    com:
      hilamiks:
        cards: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"