#base image with java runtime
#FROM openjdk:21-jdk-slim
#
##maintainer info
#MAINTAINER mike
#
##copy jar into container environment
#COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar
#
##execute the app
#ENTRYPOINT ["java", "-jar", "accounts-0.0.1-SNAPSHOT.jar"]