spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8071/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        response-timeout: 10s
        connect-timeout: 50000
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted
info:
  app:
    name: "gatewayserver"
    description: "SomeBank gateway server application"
    version: "1.0.0"
logging:
  level:
    com:
      hilamiks:
        gatewayserver: DEBUG
server:
  forward-headers-strategy: framework
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000