spring:
  application:
    name: configserver
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        native:
          search-locations: C:\.dev\config
        #search-locations: classpath:/config
        git:
          uri: https://github.com/Hilamiks/microservice-app-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
server:
  port: 8071
  forward-headers-strategy: framework
encrypt:
  key: 45D81EC1EF61DF9AD8D3E5BB397F9
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    com:
      hilamiks:
        configserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"